version: '2.1'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
